### ISSUE TITLE
segmentation violation occurs at ecsher logs command

### ISSUE THREAD

**Issue by Mic-U** [Mic-U/ecsher#34]
```
ecsher logs task --name 0d005eaa6910412db0458a3ccbb4145d  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16b13f2]

goroutine 1 [running]:
github.com/Mic-U/ecsher/cmd.getTaskLogs()
        /home/runner/work/ecsher/ecsher/cmd/logs.go:155 +0x412
github.com/Mic-U/ecsher/cmd.glob..func6(0x1c0ed20, 0xc00019cd20, 0x1, 0x3)
        /home/runner/work/ecsher/ecsher/cmd/logs.go:51 +0x95
github.com/spf13/cobra.(*Command).execute(0x1c0ed20, 0xc00019ccf0, 0x3, 0x3, 0x1c0ed20, 0xc00019ccf0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1c0efa0, 0x101a501, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/Mic-U/ecsher/cmd.Execute()
        /home/runner/work/ecsher/ecsher/cmd/root.go:38 +0x2d
main.main()
        /home/runner/work/ecsher/ecsher/main.go:21 +0x25
```

**Comment by Mic-U** [comment]
Root cause: LogConfiguration can be `nil`.

https://github.com/Mic-U/ecsher/blob/main/cmd/logs.go#L155-L158
```
if container.LogConfiguration.LogDriver != "awslogs" {
        fmt.Println("logDriver must be awslogs")
        os.Exit(1)
}
```
